### ISSUE TITLE
Warning: Unknown event handler property `onUpdateSize`. It will be ignored.

### ISSUE THREAD

**Issue by kishan143-jaiswal** [goldenyz/react-perfect-scrollbar#97] opened 2020-02-21 05:03 UTC
getting this warning in console , is any prop name is updated in the library

**Comment by goldenyz** [comment] 2020-02-21 05:35
It seems you attached a onUpdateSize to this component which doesn't support

**Comment by kishan143-jaiswal** [comment] 2020-02-21 07:20
previous version :1.5.3 i m not getting this warning while using this function as prop

**Comment by goldenyz** [comment] 2020-02-28 02:17
Because we will attach the remaining props which doesn't list in README to the inner root container DOM element

**Comment by goldenyz** [comment] 2020-02-28 02:24
I will close this issue for it is a by design behavior

**Closed as completed by goldenyz** 2020-02-28 02:24 UTC
